--1
SELECT * FROM DEPOSIT

--2
SELECT * FROM BORROW

--3
SELECT * FROM CUSTOMERS

--4
SELECT ACTNO AS AccountNo, CNAME AS CusromerName, AMOUNT FROM DEPOSIT

--5
SELECT 	LOANNO AS LoanNo, AMOUNT FROM BORROW

--6
SELECT * FROM BORROW WHERE BNAME='ANDHERI'

--7
SELECT ACTNO AS AccountNo, AMOUNT FROM DEPOSIT

--8
SELECT CNAME AS Name FROM BORROW WHERE AMOUNT > 5000

--9
SELECT CNAME AS Name FROM DEPOSIT WHERE ADATE > '1996-12-01'

--10
SELECT CNAME AS Name FROM DEPOSIT WHERE ACTNO < 105

--11
SELECT CNAME AS Name FROM CUSTOMERS WHERE CITY = 'NAGPUR' or CITY = 'DELHI'
SELECT CNAME AS Name FROM CUSTOMERS WHERE CITY in ('NAGPUR', 'DELHI')

--12
SELECT CNAME AS Name, BNAME AS Branch FROM DEPOSIT WHERE AMOUNT > 4000 and ACTNO < 105

--13
SELECT  CNAME AS Name FROM BORROW WHERE AMOUNT >= 3000 and AMOUNT <= 8000
SELECT  CNAME AS Name FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000

--14
SELECT CNAME AS Name FROM DEPOSIT WHERE BNAME <> 'ANDHERI'

--15
SELECT ACTNO AS AccountNo, CNAME AS Name, AMOUNT FROM DEPOSIT WHERE BNAME IN ('AJNI', 'KAROLBAGH', 'M.G.ROAD') AND ACTNO < 104

--PART-B 
--1
SELECT TOP 5 *FROM DEPOSIT

--2
SELECT TOP 3 *FROM DEPOSIT WHERE AMOUNT > 1000

--3
SELECT TOP 5 LOANNO AS LoanNo, CNAME AS Name FROM BORROW WHERE BNAME <> 'ANDHERI'

--4
SELECT DISTINCT CITY FROM CUSTOMERS 

--5
SELECT DISTINCT BNAME FROM BRANCH 

--PART - 3
--1
SELECT TOP 50 PERCENT * FROM BORROW 

--2
SELECT TOP 10 PERCENT * FROM DEPOSIT

--3
SELECT TOP 25 PERCENT * FROM DEPOSIT WHERE AMOUNT > 5000

--4
SELECT TOP 10 PERCENT AMOUNT FROM BORROW

--5
SELECT DISTINCT * FROM CUSTOMERS

--6
SELECT*,(AMOUNT+AMOUNT*0.1) AS 'EXTRA AMOUNT' FROM BORROW

--7
SELECT *FROM BORROW WHERE LOANNO %2=1;
